### ISSUE TITLE
Send image

### ISSUE THREAD

**Issue by ulferi** [NanotechComputers/node-red-pushover#8]
Describe the bug
After update to latest version i cant send an image with pushover.
Im sending the string in msg.image (/config/node-red/entre.jpg)
Im saving the image in a function and that works fine.

When i try this i get: "TypeError: Cannot read properties of undefined (reading 'name')"

If i change the filename or path to something wrong then i get this message: Error: ENOENT: no such file or directory, open '/config/node-red/entre1111.jpg'

So what i can understand it finds the file but cant use it for some reason

The only way to send a message is to remove the msg.image

node-RED Version
3.02

Pushover App (please complete the following information):

    Android

Package Version (please complete the following information):
@nanotechcomputers/node-red-pushover 1.2.2

Thanks

**Comment by Kevin-Deason** [comment]
It would only work with an absolute path or a HTTP(s) URL. 

Relative paths would not work.

**Comment by ulferi** [comment]
it worked in version1.0.0! But then i know! Thanks!

**Comment by ulferi** [comment]
Now i have tested it with the absolut path. 
But i get the same result!
/mnt/data/supervisor/homeassistant/node-red/entre.jpg

The file is there!

"Error: ENOENT: no such file or directory, open '/mnt/data/supervisor/homeassistant/node-red/entre.jpg'"

**Comment by Kevin-Deason** [comment]
The below error means the file does not exist
"Error: ENOENT: no such file or directory, open '/mnt/data/supervisor/homeassistant/node-red/entre.jpg'"

It might be that node-red does not have permissions to the file/folder.

**Comment by Kevin-Deason** [comment]
Hi @ulferi 

Did you perhaps come right with this?

If not, please can you provide an example flow to simulate the issue.

You can see details on exporting flows here: https://nodered.org/docs/user-guide/editor/workspace/import-export

Please do not provide any sensitive data.

**Comment by DOCaCola** [comment]
I have the same issue when trying to send a local file.
I also get an error when using a url as image source.

Here is the output from the node red log when trying to submit an url
`error TypeError: Cannot read properties of undefined (reading 'name')

    at FormData._getContentDisposition (/data/node_modules/@nanotechcomputers/node-red-pushover/node_modules/form-data/lib/form_data.js:227:40)

    at FormData._multiPartHeader (/data/node_modules/@nanotechcomputers/node-red-pushover/node_modules/form-data/lib/form_data.js:178:33)

    at FormData.append (/data/node_modules/@nanotechcomputers/node-red-pushover/node_modules/form-data/lib/form_data.js:71:21)

    at Object.postForm (/data/node_modules/@nanotechcomputers/node-red-pushover/lib/pushover.js:66:18)

    at Pushover.sendForm (/data/node_modules/@nanotechcomputers/node-red-pushover/lib/messages.js:118:25)

    at /data/node_modules/@nanotechcomputers/node-red-pushover/pushover.js:74:33

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Here is my test node
`[{"id":"121bbd0ed6ddaa8b","type":"inject","z":"a404f3b.60d5e1","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"},{"p":"image","v":"http://via.placeholder.com/350x150.jpg","vt":"str"},{"p":"imageblabla","v":"/data/test.jpg","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Test","payload":"","payloadType":"date","x":340,"y":860,"wires":[["9615359443c8d013"]]},{"id":"9615359443c8d013","type":"ntc-node-red-pushover-notifications","z":"a404f3b.60d5e1","keys":"","title":"","name":"","x":510,"y":820,"wires":[["fe0a445eaa2a6b9c"]]}]`

**Comment by ulferi** [comment]
I havent solved my issues yet!

Here are my code:
[{"id":"8043edd8f006239b","type":"change","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"Entredorr","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"Ringklocka","tot":"str"},{"t":"set","p":"image","pt":"msg","to":"/mnt/data/supervisor/media/entre.jpg","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1060,"y":1940,"wires":[["e6903ad32d49ca55"]]},{"id":"3f99d2e72a930b30","type":"http request","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","method":"GET","ret":"bin","paytoqs":"ignore","url":"http://172.xx.x.xx:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=ulf&pwd=qwer12345","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"credentials":{},"x":1200,"y":1860,"wires":[["1faf9ad41c879c18","357f60cc2f28e5be"]]},{"id":"76b66f2f84a5c061","type":"file","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","filename":"filename","filenameType":"msg","appendNewline":false,"createDir":true,"overwriteFile":"true","encoding":"none","x":840,"y":1940,"wires":[["8043edd8f006239b"]]},{"id":"1faf9ad41c879c18","type":"function","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","func":"let now = new Date().toISOString().replace(/:/g, \"-\")\n//node.warn(now);\nvar filename\nmsg.filename = '/mnt/data/supervisor/share/entre.jpg'\nreturn msg","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1350,"y":1860,"wires":[["76b66f2f84a5c061"]]},{"id":"1438985a5f3ee62b","type":"file","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","filename":"filename","filenameType":"msg","appendNewline":false,"createDir":false,"overwriteFile":"delete","encoding":"none","x":690,"y":1940,"wires":[["76b66f2f84a5c061"]]},{"id":"57a7041d9a27e36e","type":"server-state-changed","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","server":"3eac78fe.b240f","version":4,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"switch.ringklocka","entityidfiltertype":"exact","outputinitially":false,"state_type":"habool","haltifstate":"true","halt_if_type":"bool","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":"0","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":420,"y":1920,"wires":[["cdaf852b97f36b46","d333fbf91fee37f0"],[]]},{"id":"7a4f5f6972fe054d","type":"api-call-service","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"Ringklocka","server":"3eac78fe.b240f","version":5,"debugenabled":false,"domain":"switch","service":"turn_on","areaId":[],"deviceId":[],"entityId":["switch.ringklocka_mottagare"],"data":"","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"data"}],"queue":"none","x":1060,"y":1780,"wires":[[]]},{"id":"dc8ba3fed42ef98d","type":"delay","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"2","nbRateUnits":"5","rateUnits":"minute","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"allowrate":false,"outputs":1,"x":870,"y":1780,"wires":[["7a4f5f6972fe054d"]]},{"id":"cdaf852b97f36b46","type":"api-current-state","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","server":"3eac78fe.b240f","version":3,"outputs":2,"halt_if":"true","halt_if_type":"bool","halt_if_compare":"is","entity_id":"input_boolean.ringklocka_inaktiverad","state_type":"habool","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":870,"y":1840,"wires":[[],["3f99d2e72a930b30","51486eeb431ce37a"]]},{"id":"d333fbf91fee37f0","type":"time-range-switch","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","lat":"","lon":"","startTime":"22:00","endTime":"04:00","startOffset":0,"endOffset":0,"x":650,"y":1780,"wires":[[],["dc8ba3fed42ef98d"]]},{"id":"e6903ad32d49ca55","type":"ntc-node-red-pushover-notifications","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","keys":"c10e14c5dfbf0c9c","title":"Entredörr","name":"Hemma","x":1240,"y":1940,"wires":[["dc14a19a8820e47f"]]},{"id":"7fcefcde9d2ab164","type":"inject","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":420,"y":1840,"wires":[["cdaf852b97f36b46"]]},{"id":"3c5c0f03a4e7ae8f","type":"change","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"/mnt/data/docker/overlay2/d9302d075743d9b06775ef3abfaa59f6d289f5f1343281a8e4cbc181d10ffb5b/diff/opt/entre.jpg","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"/mnt/data/supervisor/homeassistant/node-red/entre.jpg","tot":"str"},{"t":"set","p":"image","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1040,"y":1980,"wires":[["e6903ad32d49ca55"]]},{"id":"dc14a19a8820e47f","type":"debug","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"debug 4","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1400,"y":1940,"wires":[]},{"id":"357f60cc2f28e5be","type":"change","z":"f0697e8b.65eb3","g":"eac291d6841a1ada","name":"","rules":[{"t":"set","p":"filename","pt":"msg","to":"/mnt/data/supervisor/media/entre.jpg","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1310,"y":1800,"wires":[["76b66f2f84a5c061"]]},{"id":"3eac78fe.b240f","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true},{"id":"c10e14c5dfbf0c9c","type":"ntc-node-red-pushover-keys","name":"Pushover"}]

**Comment by ulferi** [comment]
With correct filname and path i get this message
TypeError: Cannot read properties of undefined (reading 'name')
-rwxr-xr-x    1 root     users       106785 Nov  6 07:29 entre.jpg
the file is stored /share/entre.jpg
I have verified that the image is correct



If i change the filepath or name  to something wrong the i get
TypeError: Cannot read properties of undefined (reading 'name')
Error: ENOENT: no such file or directory, open '/share/entre1.jpg'

**Comment by DOCaCola** [comment]
I figured out a workaround. Define msg.sound in the message you are passing to the node and it works.

i.e. msg.sound = 'pushover'

**Comment by ulferi** [comment]
Thanks!
That solved it for me!

**Comment by tecbird** [comment]
same on iphone app, the workaround with msg.sound is working, but please fix it!
